### ISSUE TITLE
links

### ISSUE THREAD

**Issue by OtezVikentiy** [AshleyLv/vue-quick-menu#2]
Hello. I found a little problem IMHO on the links.
Could you please 
insert this

`<router-link :to="menuUrlList[n-1]" :target="openNewTab" :style="subMenuStyle" @mouseover.stop="mouseEnterSubMenu" @mouseout.stop="mouseOutSubMenu">
            <i :class="iconClass[n-1]" ref="icon"></i>
        </router-link>`

instead of this

`<a :href="menuUrlList[n-1]" :target="openNewTab" :style="subMenuStyle" @mouseover.stop="mouseEnterSubMenu" @mouseout.stop="mouseOutSubMenu">
            <i :class="iconClass[n-1]" ref="icon"></i>
        </a>`

it would work better without reloading page )))

**Comment by AshleyLv** [comment]
fix it in v 1.0.7
