### ISSUE TITLE
Attach URL in the buttons

### ISSUE THREAD

**Issue by ridwankustanto** [AshleyLv/vue-quick-menu#3]
I'm new at vue js, and this is Awesome!! But, I want to know how to attach the link to buttons menu? I've already defined list of array that contains URL, but I cant click it.

`<quick-menu :menuCount=menu.count :position=menu.pos :backgroundColor=menu.color :iconClass=menu.icons :menuUrlList=menu.lists></quick-menu>`

Props:

`menu: {
        count: 4,
        color: "#2f3131",
        pos: "bottom-right",
        icons: ["fa fa-envelope", "fa fa-twitter", "fa fa-linkedin", "fa fa-code"],
        lists: ["www.test.com", "www.test.com", "www.test.com", "www.test.com"]
      }`

Am I doing wrong? Thank you.

**Comment by AshleyLv** [comment]
Hi, if you just want to use the normal link, I recommend you to use v1.0.6. In the latest version I change the object of menuUrlList to support vue-router. It can support the normal link as well, but you need to change the object of menuUrlList and implement the open link part in the callback function. There is a demo page of how does it work for v1.0.7 on github. Also you can find the acceptable object of menuUrlList prop in read me.
Hope this helps^_^

Ashley

**Comment by ridwankustanto** [comment]
Wow, thanks! Now it works like a charm. ^^
